# Generated by Django 5.2.7 on 2025-11-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadServices', '0002_navitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='icon',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
