# Generated by Django 5.2.7 on 2025-11-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("squadServices", "0003_navitem_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Phone",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Type",
            new_name="userType",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
