# Generated by Django 5.2.7 on 2025-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0004_rename_phone_user_phone_rename_type_user_usertype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userType",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("SALES", "SALES"),
                    ("SUPPORT", "SUPPORT"),
                    ("NOC", "NOC"),
                    ("RATE", "RATE"),
                    ("FINANCE", "FINANCE"),
                ],
                default="SALES",
                max_length=20,
            ),
        ),
    ]
