# Generated by Django 5.2.7 on 2025-11-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0005_alter_user_usertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavUserRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userType", models.CharField(max_length=50)),
                ("read", models.BooleanField(default=False)),
                ("write", models.BooleanField(default=False)),
                ("delete", models.BooleanField(default=False)),
                ("put", models.BooleanField(default=False)),
                (
                    "navigateId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="squadServices.navitem",
                    ),
                ),
            ],
        ),
    ]
