# Generated by Django 5.2.7 on 2025-11-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0006_navuserrelation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("Promotion", "Promotion"),
                            ("Announcement", "Announcement"),
                            ("Re_engagement", "Re Engagement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("schedule", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contactNumber", models.CharField(max_length=20)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="squadServices.campaign",
                    ),
                ),
            ],
        ),
    ]
