# Generated by Django 5.2.7 on 2025-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0008_template_campaign_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
