# Generated by Django 5.2.7 on 2025-11-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0009_alter_campaign_name_alter_template_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navuserrelation",
            name="navigateId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="navigate",
                to="squadServices.navitem",
            ),
        ),
    ]
