# Generated by Django 5.2.7 on 2025-11-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0010_alter_navuserrelation_navigateid"),
    ]

    operations = [
        migrations.AddField(
            model_name="navitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="squadServices.navitem",
            ),
        ),
    ]
