# Generated by Django 5.2.7 on 2025-11-12 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0011_navitem_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("smtpHost", models.CharField(max_length=255)),
                ("smtpPort", models.IntegerField(default=587)),
                ("smtpUser", models.CharField(max_length=255)),
                ("smtpPassword", models.CharField(max_length=255)),
                ("use_tls", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_hosts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
