# Generated by Django 5.2.7 on 2025-11-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0012_emailhost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailhost",
            old_name="use_tls",
            new_name="useTls",
        ),
    ]
