# Generated by Django 5.2.7 on 2025-11-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0013_rename_use_tls_emailhost_usetls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailhost",
            name="useTls",
        ),
        migrations.AddField(
            model_name="emailhost",
            name="security",
            field=models.CharField(
                choices=[("SSL", "Ssl"), ("TLS", "Tls")], default="TLS", max_length=20
            ),
        ),
    ]
