# Generated by Django 5.2.7 on 2025-11-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0014_remove_emailhost_usetls_emailhost_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("content", models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="emailhost",
            unique_together={("smtpHost", "smtpUser")},
        ),
    ]
