# Generated by Django 5.2.7 on 2025-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0016_companycategory_companystatus_country_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
