# Generated by Django 5.2.7 on 2025-11-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0017_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="countryCode",
            field=models.CharField(max_length=100),
        ),
    ]
