# Generated by Django 5.2.7 on 2025-11-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0018_alter_country_countrycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="companycategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="companystatus",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
