# Generated by Django 5.2.7 on 2025-11-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0019_alter_company_name_alter_companycategory_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
