# Generated by Django 5.2.7 on 2025-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0021_campaign_createdat_campaign_createdby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="objective",
            field=models.CharField(
                choices=[
                    ("Promotion", "Promotion"),
                    ("Announcement", "Announcement"),
                    ("Re-engagement", "Re Engagement"),
                ],
                max_length=20,
            ),
        ),
    ]
