# Generated by Django 5.2.7 on 2025-11-24 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0022_alter_campaign_objective"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connectivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smppHost", models.CharField(max_length=255)),
                ("smppPort", models.IntegerField(default=587)),
                ("systemID", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "bindMode",
                    models.CharField(
                        choices=[
                            ("TRANSMITTER", "transmitter"),
                            ("RECEIVER", "receiver"),
                            ("TRANSCEIVER", "transceiver"),
                        ],
                        default="TRANSMITTER",
                        max_length=11,
                    ),
                ),
                ("sourceTON", models.IntegerField()),
                ("destTON", models.IntegerField()),
                ("sourceNPI", models.IntegerField()),
                ("destNPI", models.IntegerField()),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connectivity_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connectivity_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profileName", models.CharField(max_length=255)),
                (
                    "connectionType",
                    models.CharField(
                        choices=[("SMPP", "SMPP"), ("HTTP", "HTTP")],
                        default="SMPP",
                        max_length=4,
                        verbose_name="connection type",
                    ),
                ),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "companyName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="squadServices.company",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
