# Generated by Django 5.2.7 on 2025-11-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0023_connectivity_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="companyName",
            new_name="company",
        ),
    ]
