# Generated by Django 5.2.7 on 2025-11-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0024_rename_companyname_vendor_company"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emailhost",
            unique_together=set(),
        ),
    ]
