# Generated by Django 5.2.7 on 2025-11-27 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0025_alter_emailhost_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "active"),
                            ("TRIAL", "trial"),
                            ("SUSPENDED", "suspended"),
                        ],
                        default="ACTIVE",
                        max_length=11,
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("DIRECT", "direct"),
                            ("HIGH QUALITY", "high quality"),
                            ("SIM", "SIM"),
                            ("WHOLESALE", "wholesale"),
                            ("FULL", "full"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                (
                    "paymentTerms",
                    models.CharField(
                        choices=[
                            ("PREPAID", "prepaid"),
                            ("POSTPAID", "postpaid"),
                            ("NET7", "Net7"),
                            ("NET15", "Net15"),
                            ("NET30", "Net30"),
                        ],
                        default="PREPAID",
                        max_length=8,
                    ),
                ),
                (
                    "creditLimit",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
                ),
                (
                    "balanceAlertAmount",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
                ),
                ("allowNetting", models.BooleanField(default=False)),
                ("ipWhitelist", models.JSONField(blank=True, default=list)),
                ("smppUsername", models.CharField(max_length=255)),
                ("smppPassword", models.CharField(max_length=255)),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientCompany",
                        to="squadServices.company",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
