# Generated by Django 5.2.7 on 2025-11-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0026_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="internalNotes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
