# Generated by Django 5.2.7 on 2025-12-03 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0027_client_internalnotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ratePlan", models.CharField(max_length=255)),
                (
                    "currencyCode",
                    models.CharField(
                        choices=[
                            ("AUD", "AUD"),
                            ("NPR", "NPR"),
                            ("INR", "INR"),
                            ("ARD", "ARD"),
                            ("EUR", "EUR"),
                        ],
                        default="NPR",
                        max_length=4,
                        verbose_name="currency code",
                    ),
                ),
                ("MCC", models.IntegerField()),
                ("rate", models.IntegerField()),
                ("remark", models.CharField(max_length=255)),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country",
                        to="squadServices.country",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendorRate_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timeZone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeZone",
                        to="squadServices.timezone",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendorRate_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
