# Generated by Django 5.2.7 on 2025-12-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0028_vendorrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorrate",
            name="MCC",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country",
                to="squadServices.country",
            ),
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="remark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
