# Generated by Django 5.2.7 on 2025-12-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0029_alter_vendorrate_mcc_alter_vendorrate_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorrate",
            name="MNC",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorrate",
            name="countryCode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorrate",
            name="dateTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
