# Generated by Django 5.2.7 on 2025-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0031_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorrate",
            name="network",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
