# Generated by Django 5.2.7 on 2025-12-04 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0032_vendorrate_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorrate",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendorCountry",
                to="squadServices.country",
            ),
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="timeZone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeZoneVendor",
                to="squadServices.timezone",
            ),
        ),
        migrations.CreateModel(
            name="CustomerRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ratePlan", models.CharField(max_length=255)),
                (
                    "currencyCode",
                    models.CharField(
                        choices=[
                            ("AUD", "AUD"),
                            ("NPR", "NPR"),
                            ("INR", "INR"),
                            ("ARD", "ARD"),
                            ("EUR", "EUR"),
                        ],
                        default="NPR",
                        max_length=4,
                        verbose_name="currency code",
                    ),
                ),
                ("countryCode", models.IntegerField(blank=True, null=True)),
                ("MCC", models.IntegerField(blank=True, null=True)),
                ("MNC", models.IntegerField(blank=True, null=True)),
                ("rate", models.IntegerField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                ("dateTime", models.DateTimeField(blank=True, null=True)),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countryCustomer",
                        to="squadServices.country",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customerRate_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timeZone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeZoneCustomer",
                        to="squadServices.timezone",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customerRate_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
