# Generated by Django 5.2.7 on 2025-12-05 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0033_alter_vendorrate_country_alter_vendorrate_timezone_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SMPPAccount", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("countryCode", models.CharField(max_length=255)),
                ("network", models.CharField(max_length=255)),
                ("MCC", models.CharField(max_length=255)),
                ("MNC", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("effectiveFrom", models.CharField(max_length=255)),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mappingSetup_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mappingSetup_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
