# Generated by Django 5.2.7 on 2025-12-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0034_mappingsetup"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingsetup",
            name="currencyCode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="MCC",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="MNC",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="SMPPAccount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="countryCode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="effectiveFrom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="network",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="mappingsetup",
            name="price",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
