# Generated by Django 5.2.7 on 2025-12-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0035_mappingsetup_currencycode_alter_mappingsetup_mcc_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mappingsetup",
            name="currencyCode",
        ),
    ]
