# Generated by Django 5.2.7 on 2025-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0036_remove_mappingsetup_currencycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingsetup",
            name="timeZone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
