# Generated by Django 5.2.7 on 2025-12-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0037_mappingsetup_timezone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mappingsetup",
            old_name="effectiveFrom",
            new_name="effectiveForm",
        ),
    ]
