# Generated by Django 5.2.7 on 2025-12-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0038_rename_effectivefrom_mappingsetup_effectiveform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorrate",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="currencyCode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="timeZone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
