# Generated by Django 5.2.7 on 2025-12-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0039_alter_vendorrate_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorrate",
            name="rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
