# Generated by Django 5.2.7 on 2025-12-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0040_alter_vendorrate_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mappingsetup",
            old_name="SMPPAccount",
            new_name="rate",
        ),
        migrations.RenameField(
            model_name="mappingsetup",
            old_name="price",
            new_name="ratePlan",
        ),
    ]
