# Generated by Django 5.2.7 on 2025-12-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0041_rename_smppaccount_mappingsetup_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mappingsetup",
            old_name="effectiveForm",
            new_name="dateTime",
        ),
    ]
