# Generated by Django 5.2.7 on 2025-12-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0042_rename_effectiveform_mappingsetup_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navitem",
            name="order",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
