# Generated by Django 5.2.7 on 2025-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0043_alter_navitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navitem",
            name="order",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
