# Generated by Django 5.2.7 on 2025-12-12 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0045_operators"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Connectivity",
            new_name="SMPP",
        ),
        migrations.AddField(
            model_name="vendor",
            name="smpp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="smpp",
                to="squadServices.smpp",
            ),
        ),
    ]
