# Generated by Django 5.2.7 on 2025-12-14 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0047_userloginhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userloginhistory",
            options={"ordering": ["-loggedAt"]},
        ),
        migrations.RenameField(
            model_name="userloginhistory",
            old_name="ip_address",
            new_name="ipAddress",
        ),
        migrations.RenameField(
            model_name="userloginhistory",
            old_name="logged_at",
            new_name="loggedAt",
        ),
        migrations.RenameField(
            model_name="userloginhistory",
            old_name="user_agent",
            new_name="userAgent",
        ),
        migrations.AlterField(
            model_name="userloginhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="loginHistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
