# Generated by Django 5.2.7 on 2025-12-15 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0048_alter_userloginhistory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("priority", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="countryCustomRoutes",
                        to="squadServices.country",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customRoute_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="operatorCustomRoutes",
                        to="squadServices.operators",
                    ),
                ),
                (
                    "orginatingClient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orginatingClientCustomRoutes",
                        to="squadServices.country",
                    ),
                ),
                (
                    "orginatingCompany",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orginatingCompanyCustomRoutes",
                        to="squadServices.company",
                    ),
                ),
                (
                    "terminatingCompany",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="terminatingCompanyCustomRoutes",
                        to="squadServices.company",
                    ),
                ),
                (
                    "terminatingVendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="terminatingVendorCustomRoutes",
                        to="squadServices.vendor",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customRoute_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
