# Generated by Django 5.2.7 on 2026-01-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0049_customroute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="companycategory",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="companystatus",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="customerrate",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="customroute",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="emailhost",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="entity",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="mappingsetup",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="navitem",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="network",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="operators",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="smpp",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="template",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="timezone",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterModelOptions(
            name="vendorrate",
            options={"ordering": ["-updatedAt"]},
        ),
        migrations.AlterField(
            model_name="customroute",
            name="orginatingClient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orginatingClientCustomRoutes",
                to="squadServices.client",
            ),
        ),
    ]
