# Generated by Django 5.2.7 on 2026-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0051_smsmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="systemId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
