# Generated by Django 5.2.7 on 2026-01-30 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0052_smsmessage_systemid"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="smpp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="smsMessageSmpp",
                to="squadServices.smpp",
            ),
        ),
    ]
