# Generated by Django 5.2.7 on 2026-01-31 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0053_smsmessage_smpp"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientSMSMessage",
                to="squadServices.client",
            ),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendorSMSMessage",
                to="squadServices.vendor",
            ),
        ),
    ]
