# Generated by Django 5.2.7 on 2026-02-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0054_smsmessage_client_smsmessage_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="ipWhitelist",
        ),
        migrations.AlterModelTable(
            name="client",
            table="squadServices_client",
        ),
        migrations.AlterModelTable(
            name="customroute",
            table="squadServices_customroute",
        ),
        migrations.AlterModelTable(
            name="smsmessage",
            table="squadServices_smsmessage",
        ),
        migrations.CreateModel(
            name="IpWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(unpack_ipv4=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipWhitelist",
                        to="squadServices.client",
                    ),
                ),
            ],
            options={
                "db_table": "squadServices_ipwhitelist",
            },
        ),
    ]
