# Generated by Django 5.2.7 on 2026-02-05 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0055_remove_client_ipwhitelist_alter_client_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipwhitelist",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ipwhitelist",
            name="createdBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientIpWhiteList_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ipwhitelist",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ipwhitelist",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ipwhitelist",
            name="updatedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientIpWhiteList_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
