# Generated by Django 5.2.7 on 2026-02-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0056_ipwhitelist_createdat_ipwhitelist_createdby_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="characterCount",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="encoding",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="segmentNumber",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
