# Generated by Django 5.2.7 on 2026-02-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0057_smsmessage_charactercount_smsmessage_encoding_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smsmessage",
            options={"ordering": ["-updatedAt"]},
        ),
    ]
