# Generated by Django 5.2.7 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0058_alter_smsmessage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="message_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
