# Generated by Django 5.2.7 on 2026-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0061_alter_notification_description_userlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
    ]
