# Generated by Django 5.2.7 on 2026-02-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0062_userlog_isdeleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="businessEntity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="squadServices.entity",
            ),
        ),
    ]
