# Generated by Django 5.2.7 on 2026-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0063_alter_company_businessentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="MCC",
            field=models.CharField(max_length=100),
        ),
    ]
