# Generated by Django 5.2.7 on 2026-02-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0064_alter_country_mcc"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSMessagePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_no", models.IntegerField()),
                ("part_total", models.IntegerField()),
                ("udh_ref", models.IntegerField()),
                ("esm_class", models.IntegerField(default=0)),
                ("short_message", models.BinaryField()),
                (
                    "submit_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SUBMITTED", "Submitted"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                (
                    "vendor_msg_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vendor_submit_status", models.IntegerField(blank=True, null=True)),
                ("submit_attempts", models.IntegerField(default=0)),
                ("last_submit_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="squadServices.smsmessage",
                    ),
                ),
            ],
        ),
    ]
