# Generated by Django 5.2.7 on 2026-02-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0065_smsmessagepart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessagepart",
            name="submit_status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("DELIVERED", "Delivered"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
    ]
