# Generated by Django 5.2.7 on 2026-03-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0066_alter_smsmessagepart_submit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="ratePlanName",
            field=models.CharField(
                blank=True,
                help_text="Type the exact name of the ratePlan used in the VendorRate table",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor",
                to="squadServices.company",
            ),
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="MCC",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vendorrate",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
