# Generated by Django 5.2.7 on 2026-03-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0067_vendor_rateplanname_alter_vendor_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customroute",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countryCustomRoutes",
                to="squadServices.country",
            ),
        ),
        migrations.AlterField(
            model_name="customroute",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operatorCustomRoutes",
                to="squadServices.operators",
            ),
        ),
        migrations.AlterField(
            model_name="customroute",
            name="orginatingClient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orginatingClientCustomRoutes",
                to="squadServices.client",
            ),
        ),
        migrations.AlterField(
            model_name="customroute",
            name="orginatingCompany",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orginatingCompanyCustomRoutes",
                to="squadServices.company",
            ),
        ),
        migrations.AlterField(
            model_name="customroute",
            name="terminatingCompany",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminatingCompanyCustomRoutes",
                to="squadServices.company",
            ),
        ),
        migrations.AlterField(
            model_name="customroute",
            name="terminatingVendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminatingVendorCustomRoutes",
                to="squadServices.vendor",
            ),
        ),
    ]
