# Generated by Django 5.2.7 on 2026-03-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0068_alter_customroute_country_alter_customroute_operator_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="operators",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="countryOperators",
                to="squadServices.country",
            ),
        ),
    ]
