# Generated by Django 5.2.7 on 2026-03-08 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0069_alter_operators_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transactionType",
                    models.CharField(
                        choices=[
                            ("DEDUCTION", "Deduction"),
                            ("REFUND", "Refund"),
                            ("TOPUP", "Top-Up"),
                        ],
                        default="DEDUCTION",
                        max_length=20,
                    ),
                ),
                (
                    "segments",
                    models.IntegerField(
                        blank=True, help_text="Number of SMS parts billed", null=True
                    ),
                ),
                (
                    "ratePerSegment",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("balanceAfter", models.DecimalField(decimal_places=4, max_digits=10)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("isDeleted", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="squadServices.client",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientTransactionCreated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="squadServices.smsmessage",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientTransactionUpdated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transactionType",
                    models.CharField(
                        choices=[
                            ("DEDUCTION", "Deduction"),
                            ("REFUND", "Refund"),
                            ("TOPUP", "Top-Up"),
                        ],
                        default="DEDUCTION",
                        max_length=20,
                    ),
                ),
                ("segments", models.IntegerField(blank=True, null=True)),
                (
                    "ratePerSegment",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=10)),
                ("balanceAfter", models.DecimalField(decimal_places=4, max_digits=10)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("isDeleted", models.BooleanField(default=False)),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendorTransactionCreated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="squadServices.smsmessage",
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendorTransactionUpdated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="squadServices.vendor",
                    ),
                ),
            ],
        ),
    ]
