# Generated by Django 5.2.7 on 2026-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0070_clienttransaction_vendortransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="ratePlanName",
            field=models.CharField(
                blank=True,
                help_text="Type the exact name of the ratePlan used in the customerRate table",
                max_length=255,
                null=True,
            ),
        ),
    ]
