# Generated by Django 5.2.7 on 2026-03-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0071_client_rateplanname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clienttransaction",
            old_name="balanceAfter",
            new_name="balanceSpent",
        ),
        migrations.RenameField(
            model_name="vendortransaction",
            old_name="balanceAfter",
            new_name="balanceSpent",
        ),
    ]
