# Generated by Django 5.2.7 on 2026-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0072_rename_balanceafter_clienttransaction_balancespent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="usedCustomerCredit",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Tracks total amount this company owes you (Customer spend)",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="usedVendorCredit",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Tracks total amount you owe this company (Vendor spend)",
                max_digits=18,
            ),
        ),
    ]
