# Generated by Django 5.2.7 on 2026-03-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0073_company_usedcustomercredit_company_usedvendorcredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="usedCredit",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Tracks how much this specific SMPP account has spent",
                max_digits=18,
            ),
        ),
    ]
