# Generated by Django 5.2.7 on 2026-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0074_client_usedcredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessagepart",
            name="text",
            field=models.TextField(
                blank=True,
                help_text="The decoded text chunk for this segment",
                null=True,
            ),
        ),
    ]
