# Generated by Django 5.2.7 on 2026-03-15 18:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0075_smsmessagepart_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailedSMSReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("senderId", models.CharField(blank=True, max_length=50, null=True)),
                ("text_message_id", models.CharField(db_index=True, max_length=255)),
                ("vendor_msg_id", models.CharField(db_index=True, max_length=255)),
                ("text", models.TextField(blank=True, null=True)),
                ("part_total", models.IntegerField()),
                (
                    "clientRate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Price per segment for client",
                        max_digits=12,
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_charge",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="The actual cost of this message",
                        max_digits=12,
                    ),
                ),
                ("countryMCC", models.CharField(blank=True, max_length=100, null=True)),
                ("operatorMNC", models.CharField(default="All", max_length=100)),
                ("destination", models.CharField(db_index=True, max_length=50)),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "vendorRate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Price per segment from vendor",
                        max_digits=12,
                    ),
                ),
                (
                    "vendor_charge",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="What the vendor charged you",
                        max_digits=12,
                    ),
                ),
                (
                    "submitStatus",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("DELIVERED", "Delivered"),
                            ("SUBMITTED", "Submitted"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("request_time", models.DateTimeField(blank=True, null=True)),
                ("delivery_time", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_row",
                        to="squadServices.smsmessage",
                    ),
                ),
            ],
            options={
                "db_table": "squadServices_detailed_report",
                "ordering": ["-request_time"],
            },
        ),
    ]
