# Generated by Django 5.2.7 on 2026-03-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0076_detailedsmsreport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
    ]
