# Generated by Django 5.2.7 on 2026-03-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0077_alter_country_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="emailServer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="squadServices.emailhost",
            ),
        ),
    ]
