# Generated by Django 5.2.7 on 2026-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0078_emailtemplate_emailserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
