# Generated by Django 5.2.7 on 2026-03-29 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0081_clientinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinvoice",
            name="accountManager",
            field=models.ForeignKey(
                blank=True,
                help_text="The internal user managing this client/invoice.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
