# Generated by Django 5.2.7 on 2026-03-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0082_clientinvoice_accountmanager"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientinvoice",
            name="totalSegments",
            field=models.IntegerField(default=0),
        ),
    ]
