# Generated by Django 5.2.7 on 2026-03-29 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0083_clientinvoice_totalsegments"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billingPeriodStart", models.DateField()),
                ("billingPeriodEnd", models.DateField()),
                ("invoiceDate", models.DateField()),
                ("invoiceNumber", models.CharField(max_length=50, unique=True)),
                (
                    "totalAmount",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
                ),
                ("totalSegments", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATED", "Generated"),
                            ("SENT", "Sent"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "invoicePdf",
                    models.FileField(
                        blank=True, null=True, upload_to="invoices/clients/%Y/%m/"
                    ),
                ),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "accountManager",
                    models.ForeignKey(
                        blank=True,
                        help_text="The internal user managing this vendor/invoice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_vendorInvoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendorInvoice_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendorInvoices",
                        to="squadServices.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "squadServices_vendorinvoice",
                "ordering": ["-createdAt"],
            },
        ),
    ]
