# Generated by Django 5.2.7 on 2026-03-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0084_vendorinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="bankAccountDetail",
            field=models.TextField(
                blank=True,
                help_text="Store Bank Name, Account Number, and Routing/Swift codes here.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="businessAddress",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="companyLogo",
            field=models.ImageField(blank=True, null=True, upload_to="entities/logos/"),
        ),
        migrations.AddField(
            model_name="entity",
            name="companyName",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entity",
            name="emailAddress",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="invoiceNumber",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="entity",
            name="legalEntityName",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entity",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="vatRegistrationNumber",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="weekCommencing",
            field=models.CharField(
                choices=[("SUNDAY", "Sunday"), ("MONDAY", "Monday")],
                default="MONDAY",
                max_length=10,
            ),
        ),
    ]
