# Generated by Django 5.2.7 on 2026-03-30 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0085_entity_bankaccountdetail_entity_businessaddress_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicesetup",
            name="businessEntity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entityInvoiceSetups",
                to="squadServices.entity",
            ),
        ),
    ]
