# Generated by Django 5.2.7 on 2026-03-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0086_alter_invoicesetup_businessentity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="name",
        ),
    ]
