# Generated by Django 5.2.7 on 2026-04-02 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0087_remove_entity_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DLREvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("event_type", models.CharField(max_length=30)),
                ("segment_number", models.IntegerField(blank=True, null=True)),
                ("status_code", models.CharField(blank=True, max_length=10, null=True)),
                ("status_description", models.TextField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="squadServices.smsmessage",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="squadServices.smsmessagepart",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                ("provider", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(max_length=20)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="squadServices.smsmessage",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="squadServices.smsmessagepart",
                    ),
                ),
            ],
        ),
    ]
