# Generated by Django 5.2.7 on 2026-04-02 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0090_alter_smsmessage_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20, null=True)),
                ("to_status", models.CharField(max_length=20)),
                ("changed_by", models.CharField(default="system", max_length=100)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="squadServices.smsmessage",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="squadServices.smsmessagepart",
                    ),
                ),
            ],
            options={
                "db_table": "message_audit_log",
                "indexes": [
                    models.Index(
                        fields=["message"], name="message_aud_message_7028dc_idx"
                    ),
                    models.Index(
                        fields=["segment"], name="message_aud_segment_472321_idx"
                    ),
                ],
            },
        ),
    ]
