# Generated by Django 5.2.7 on 2026-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0091_messageauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dlrevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                    ("UNDELIVERABLE", "Undeliverable"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="messageattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATTEMPTING", "Attempting"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                    ("DELIVERED", "Delivered"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="messageauditlog",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("partially_delivered", "Partially Delivered"),
                    ("QUEUED", "Part Queued"),
                    ("SUBMITTED", "Part Submitted"),
                    ("DELIVERED", "Part Delivered"),
                    ("FAILED", "Part Failed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="messageauditlog",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("partially_delivered", "Partially Delivered"),
                    ("QUEUED", "Part Queued"),
                    ("SUBMITTED", "Part Submitted"),
                    ("DELIVERED", "Part Delivered"),
                    ("FAILED", "Part Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
