# Generated by Django 5.2.7 on 2026-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0092_alter_dlrevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dlrevent",
            options={"ordering": ["-received_at"]},
        ),
        migrations.AlterModelOptions(
            name="messageattempt",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterModelOptions(
            name="smsmessagepart",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="client",
            name="enableDlr",
            field=models.BooleanField(
                default=True,
                help_text="Enable to allow this client to receive final Delivery Receipts. Disable to save server resources.",
            ),
        ),
    ]
