# Generated by Django 5.2.7 on 2026-04-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0093_alter_dlrevent_options_alter_messageattempt_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="smsmessage",
            name="clientDlrPushed",
            field=models.BooleanField(
                default=False,
                help_text="True if we have successfully forwarded the final DLR back to the client.",
            ),
        ),
        migrations.AddField(
            model_name="smsmessage",
            name="sendClientDlr",
            field=models.BooleanField(
                default=False,
                help_text="True if the client requested a DLR AND their account is allowed to receive them.",
            ),
        ),
    ]
