# Generated by Django 5.2.7 on 2026-04-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0094_smsmessage_clientdlrpushed_smsmessage_sendclientdlr"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipartBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_id", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=50)),
                ("ref_num", models.IntegerField()),
                ("total_parts", models.IntegerField()),
                ("part_num", models.IntegerField()),
                ("text_chunk", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {
                    ("system_id", "destination", "ref_num", "part_num")
                },
            },
        ),
    ]
