# Generated by Django 5.2.7 on 2026-04-08 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0095_multipartbuffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="external_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
            ),
        ),
    ]
