# Generated by Django 5.2.7 on 2026-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0096_alter_smsmessage_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="invoicePolicy",
            field=models.CharField(
                choices=[
                    ("ON ATTEMPT", "on attempt"),
                    ("ON SUBMIT", "on submit"),
                    ("ON DELIVERED", "on delivered"),
                ],
                default="ON ATTEMPT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clienttransaction",
            name="chargePolicy",
            field=models.CharField(
                choices=[
                    ("ON ATTEMPT", "on attempt"),
                    ("ON SUBMIT", "on submit"),
                    ("ON DELIVERED", "on delivered"),
                ],
                default="ON ATTEMPT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clienttransaction",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="clienttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("DELIVERED", "Delivered"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clienttransaction",
            name="taxAmount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="invoicePolicy",
            field=models.CharField(
                choices=[
                    ("ON ATTEMPT", "on attempt"),
                    ("ON SUBMIT", "on submit"),
                    ("ON DELIVERED", "on delivered"),
                ],
                default="ON ATTEMPT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendortransaction",
            name="chargePolicy",
            field=models.CharField(
                choices=[
                    ("ON ATTEMPT", "on attempt"),
                    ("ON SUBMIT", "on submit"),
                    ("ON DELIVERED", "on delivered"),
                ],
                default="ON ATTEMPT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendortransaction",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="vendortransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("DELIVERED", "Delivered"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendortransaction",
            name="taxAmount",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="smsmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("submitted", "Submitted"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                    ("partially_delivered", "Partially Delivered"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
