# Generated by Django 5.2.7 on 2026-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0097_client_invoicepolicy_clienttransaction_chargepolicy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clienttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("submitted", "Submitted"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smsmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("submitted", "Submitted"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vendortransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("submitted", "Submitted"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
