# Generated by Django 5.2.7 on 2026-04-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0098_alter_clienttransaction_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="bindStatus",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")],
                default="OFFLINE",
                help_text="Live indicator of whether the client is currently connected to our SMPP server.",
                max_length=10,
            ),
        ),
    ]
