# Generated by Django 5.2.7 on 2026-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0099_client_bindstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="enquire",
            field=models.IntegerField(
                default=30, help_text="Time in seconds between ENQUIRE_LINK requests"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="rate",
            field=models.IntegerField(
                default=0, help_text="Max SUBMIT_SM per second (0=unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="timeOut",
            field=models.IntegerField(
                default=30,
                help_text="Time in seconds before SMPP connection times out due to inactivity",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="window",
            field=models.IntegerField(
                default=10, help_text="Max outstanding unacked SUBMIT_SM"
            ),
        ),
    ]
