# Generated by Django 5.2.7 on 2026-04-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0101_puskarclient"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="puskarclient",
            table="squadServices_puskar_client",
        ),
    ]
