# Generated by Django 5.2.7 on 2026-04-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0102_alter_puskarclient_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="puskarclient",
            old_name="FsmppPassword",
            new_name="FsmppUsername",
        ),
    ]
