# Generated by Django 5.2.7 on 2026-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0103_rename_fsmpppassword_puskarclient_fsmppusername"),
    ]

    operations = [
        migrations.AddField(
            model_name="puskarclient",
            name="smppPassword",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
