# Generated by Django 5.2.7 on 2026-04-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0104_puskarclient_smpppassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorrate",
            name="MCC",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
