# Generated by Django 5.2.7 on 2026-04-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0105_alter_vendorrate_mcc"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="squadServices.vendor",
            ),
        ),
    ]
