# Generated by Django 5.2.7 on 2026-04-20 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0106_campaign_vendor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clienttransaction",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterModelOptions(
            name="vendortransaction",
            options={"ordering": ["-createdAt"]},
        ),
        migrations.AlterField(
            model_name="vendortransaction",
            name="currency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="ClientPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maxTps",
                    models.IntegerField(
                        default=50, help_text="Max SUBMIT_SM per second (0=unlimited)"
                    ),
                ),
                (
                    "maxWindowPerSession",
                    models.IntegerField(
                        default=10, help_text="Max outstanding unacked SUBMIT_SM"
                    ),
                ),
                (
                    "maxWindowGlobal",
                    models.IntegerField(
                        default=100,
                        help_text="Max outstanding unacked SUBMIT_SM across all sessions",
                    ),
                ),
                (
                    "maxSessions",
                    models.IntegerField(
                        default=2,
                        help_text="Max concurrent SMPP sessions for this client",
                    ),
                ),
                (
                    "idleTimeoutSec",
                    models.IntegerField(
                        default=60,
                        help_text="Time in seconds before SMPP connection times out due to inactivity",
                    ),
                ),
                (
                    "submitTimeoutSec",
                    models.IntegerField(
                        default=30,
                        help_text="Time in seconds before a SUBMIT_SM is considered timed out if no response is received",
                    ),
                ),
                (
                    "maxQueueDepth",
                    models.IntegerField(
                        default=1000,
                        help_text="Max number of messages to queue for this client when rate limits are exceeded",
                    ),
                ),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientPolicy",
                        to="squadServices.client",
                    ),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientPolicy_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientPolicy_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "squadServices_ClientPolicy",
                "ordering": ["-updatedAt"],
            },
        ),
        migrations.CreateModel(
            name="VendorPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sourceAddrTon",
                    models.IntegerField(default=5, help_text="Source Addr Ton"),
                ),
                (
                    "sourceAddrNpi",
                    models.IntegerField(default=0, help_text="Source Addr NPI"),
                ),
                (
                    "destAddrTon",
                    models.IntegerField(default=1, help_text="Destination Addr Ton"),
                ),
                (
                    "destAddrNpi",
                    models.IntegerField(default=1, help_text="Destination Addr NPI"),
                ),
                ("addrTon", models.IntegerField(blank=True, default=1, null=True)),
                ("addrNpi", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "rateTps",
                    models.IntegerField(
                        default=50, help_text="Rate/TPS (Max messages per second)"
                    ),
                ),
                (
                    "sendQueueLimit",
                    models.IntegerField(
                        default=10, help_text="Send Queue Limit (Window Size)"
                    ),
                ),
                (
                    "delayTime",
                    models.FloatField(default=0.0, help_text="Delay Time (Seconds)"),
                ),
                (
                    "responseTimeout",
                    models.FloatField(
                        default=30.0, help_text="Response Timeout (Seconds)"
                    ),
                ),
                (
                    "enquireLinkInterval",
                    models.FloatField(default=30.0, help_text="Enquire Link (Seconds)"),
                ),
                (
                    "connectionTimeout",
                    models.FloatField(
                        default=10.0, help_text="Connection Timeout (Seconds)"
                    ),
                ),
                (
                    "connectionRetryDelay",
                    models.FloatField(
                        default=5.0, help_text="Connection Retry Delay (Seconds)"
                    ),
                ),
                (
                    "connectionRetryCount",
                    models.IntegerField(default=3, help_text="Connection Retry Count"),
                ),
                (
                    "bindRetryDelay",
                    models.FloatField(
                        default=5.0, help_text="Bind Retry Delay (Seconds)"
                    ),
                ),
                (
                    "bindRetryCount",
                    models.IntegerField(default=3, help_text="Bind Retry Count"),
                ),
                (
                    "connectionRecoveryDelay",
                    models.FloatField(
                        default=60.0, help_text="Connection Recovery Delay (Seconds)"
                    ),
                ),
                (
                    "logLevel",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        help_text="Log Level",
                        max_length=10,
                    ),
                ),
                (
                    "tlvTag",
                    models.CharField(
                        blank=True,
                        help_text="TLV Tag (e.g. 0x1401)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tlvValue",
                    models.CharField(
                        blank=True, help_text="TLV Value", max_length=255, null=True
                    ),
                ),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "createdBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendorPolicy_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendorPolicy_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="squadServices.vendor",
                    ),
                ),
            ],
        ),
    ]
