# Generated by Django 5.2.7 on 2026-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0107_alter_clienttransaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientpolicy",
            name="senderIdPolicy",
            field=models.CharField(default="approvedOnly", max_length=20),
        ),
    ]
