# Generated by Django 5.2.7 on 2026-04-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0108_clientpolicy_senderidpolicy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="enquire",
        ),
        migrations.RemoveField(
            model_name="client",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="client",
            name="timeOut",
        ),
        migrations.RemoveField(
            model_name="client",
            name="window",
        ),
    ]
