# Generated by Django 5.2.7 on 2026-04-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0109_remove_client_enquire_remove_client_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="country",
            name="iso2",
            field=models.CharField(default="NP", help_text="e.g. NP", max_length=2),
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="subRegion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="operators",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operators",
            name="operatorCode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="operators",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="MCC",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vendorpolicy",
            name="delayTime",
            field=models.FloatField(default=10.0, help_text="Delay Time (Seconds)"),
        ),
        migrations.CreateModel(
            name="OperatorNetworkCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MCC",
                    models.CharField(help_text="Mobile Country Code", max_length=3),
                ),
                (
                    "MNC",
                    models.CharField(help_text="Mobile Network Code", max_length=3),
                ),
                (
                    "networkName",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "networkType",
                    models.CharField(
                        choices=[
                            ("GSM", "GSM"),
                            ("LTE", "LTE"),
                            ("5G", "5G"),
                            ("CDMA", "CDMA"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("isPrimary", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="squadServices.country",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_codes",
                        to="squadServices.operators",
                    ),
                ),
            ],
            options={
                "db_table": "operator_network_codes",
                "indexes": [
                    models.Index(
                        fields=["MCC", "MNC"], name="operator_ne_MCC_a23e9d_idx"
                    ),
                    models.Index(
                        fields=["country", "MCC", "MNC"],
                        name="operator_ne_country_1b896d_idx",
                    ),
                ],
                "unique_together": {("operator", "MCC", "MNC")},
            },
        ),
    ]
