# Generated by Django 5.2.7 on 2026-04-21 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0110_country_isactive_country_iso2_country_region_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operatornetworkcode",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="operatornetworkcode",
            old_name="updated_at",
            new_name="updatedAt",
        ),
        migrations.AddField(
            model_name="operatornetworkcode",
            name="createdBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operatorNetworkCode_updated_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="operatornetworkcode",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operatornetworkcode",
            name="updatedBy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operatorNetworkCode_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
