# Generated by Django 5.2.7 on 2026-04-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0111_rename_created_at_operatornetworkcode_createdat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="operatornetworkcode",
            name="effectiveFrom",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operatornetworkcode",
            name="effectiveTo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operatornetworkcode",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
