# Generated by Django 5.2.7 on 2026-04-22 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0112_operatornetworkcode_effectivefrom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="MCC",
        ),
        migrations.AlterField(
            model_name="company",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companyCategorys",
                to="squadServices.companycategory",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="squadServices.state",
            ),
        ),
    ]
