# Generated by Django 5.2.7 on 2026-04-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0113_remove_country_mcc_alter_company_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operators",
            name="MNC",
        ),
    ]
