# Generated by Django 5.2.7 on 2026-04-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0114_remove_operators_mnc"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="operatornetworkcode",
            new_name="squadServic_MCC_e986fc_idx",
            old_name="operator_ne_MCC_a23e9d_idx",
        ),
        migrations.RenameIndex(
            model_name="operatornetworkcode",
            new_name="squadServic_country_25cc4c_idx",
            old_name="operator_ne_country_1b896d_idx",
        ),
        migrations.AlterModelTable(
            name="operatornetworkcode",
            table="squadServices_operatornetworkcode",
        ),
    ]
