# Generated by Django 5.2.7 on 2026-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0115_rename_operator_ne_mcc_a23e9d_idx_squadservic_mcc_e986fc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerrate",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
