# Generated by Django 5.2.7 on 2026-04-23 11:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0116_alter_customerrate_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("submitted", "Submitted"),
                    ("failed", "Failed"),
                    ("delivered", "Delivered"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="smsmessagepart",
            name="submit_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("DELIVERED", "Delivered"),
                    ("SUBMITTED", "Submitted"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientSession",
            fields=[
                (
                    "sessionId",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("systemId", models.CharField(max_length=50)),
                ("bindType", models.CharField(max_length=20)),
                ("remoteIp", models.CharField(max_length=45)),
                ("remotePort", models.IntegerField()),
                (
                    "connectedAt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("boundAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_activityAt", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="ONLINE", max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to="squadServices.client",
                    ),
                ),
            ],
            options={
                "db_table": "clientSessions",
            },
        ),
    ]
