# Generated by Django 5.2.7 on 2026-04-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0117_alter_smsmessage_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientsession",
            options={"ordering": ["-connectedAt"]},
        ),
        migrations.RemoveField(
            model_name="currency",
            name="country",
        ),
        migrations.AddField(
            model_name="currency",
            name="currencyCode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="decimalPlaces",
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="numericCode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
