# Generated by Django 5.2.7 on 2026-04-26 07:01

import squadServices.models.company
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "squadServices",
            "0118_alter_clientsession_options_remove_currency_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="billingEmail",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    squadServices.models.company.validate_comma_separated_emails
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyEmail",
            field=models.CharField(
                blank=True,
                help_text="Separate multiple emails with a comma.",
                max_length=255,
                null=True,
                validators=[
                    squadServices.models.company.validate_comma_separated_emails
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="lowBalanceAlertEmail",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    squadServices.models.company.validate_comma_separated_emails
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="ratesEmail",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    squadServices.models.company.validate_comma_separated_emails
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="supportEmail",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    squadServices.models.company.validate_comma_separated_emails
                ],
            ),
        ),
    ]
