# Generated by Django 5.2.7 on 2026-04-27 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0119_alter_company_billingemail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="vendor",
        ),
        migrations.AddField(
            model_name="campaign",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="squadServices.client",
            ),
        ),
    ]
