# Generated by Django 5.2.7 on 2026-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0120_remove_campaign_vendor_campaign_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dlrevent",
            name="status_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
