# Generated by Django 5.2.7 on 2026-04-28 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0121_alter_dlrevent_status_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companyName",
                    models.CharField(default="Squad Telekom LLC", max_length=255),
                ),
                (
                    "defaultLanguage",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "defaultTimezone",
                    models.CharField(
                        default="UTC",
                        help_text="Standard timezone string (e.g., UTC, Europe/London)",
                        max_length=50,
                    ),
                ),
                ("dateFormat", models.CharField(default="YYYY-MM-DD", max_length=20)),
                (
                    "datetimeFormat",
                    models.CharField(default="YYYY-MM-DD HH:MM:SS", max_length=50),
                ),
                (
                    "baseCurrency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro (EUR)"),
                            ("USD", "US Dollar (USD)"),
                            ("GBP", "British Pound (GBP)"),
                            ("NPR", "Nepalese Rupee (NPR)"),
                        ],
                        default="EUR",
                        max_length=10,
                    ),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "updatedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generalSetting_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "General Setting",
                "verbose_name_plural": "General Settings",
            },
        ),
    ]
