# Generated by Django 5.2.7 on 2026-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0122_generalsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="bindStatus",
            field=models.BooleanField(
                default=False,
                help_text="READ ONLY: True if the SMPP server is currently connected to this vendor.",
            ),
        ),
    ]
