# Generated by Django 5.2.7 on 2026-04-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0123_vendor_bindstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorpolicy",
            name="maxSession",
            field=models.IntegerField(
                default=2, help_text="Max concurrent SMPP sessions for this client"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="bindStatus",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("OFFLINE", "Offline")],
                default="OFFLINE",
                help_text="Live indicator of whether the vendor is currently connected to our SMPP server.",
                max_length=10,
            ),
        ),
    ]
