# Generated by Django 5.2.7 on 2026-04-29 17:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0124_vendorpolicy_maxsession_alter_vendor_bindstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorSession",
            fields=[
                (
                    "sessionId",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gatewayIp", models.CharField(max_length=45)),
                ("bindType", models.CharField(max_length=20)),
                (
                    "connectedAt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("disconnectedAt", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="ONLINE", max_length=20)),
                ("error_reason", models.TextField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="squadServices.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "vendorSessions",
                "ordering": ["-connectedAt"],
            },
        ),
    ]
