# Generated by Django 5.2.7 on 2026-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0125_vendorsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="lastAttemptAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="lastRetryAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
