# Generated by Django 5.2.7 on 2026-05-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0126_vendor_lastattemptat_vendor_lastretryat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorpolicy",
            name="addrNpi",
        ),
        migrations.RemoveField(
            model_name="vendorpolicy",
            name="addrTon",
        ),
        migrations.RemoveField(
            model_name="vendorpolicy",
            name="destAddrNpi",
        ),
        migrations.RemoveField(
            model_name="vendorpolicy",
            name="destAddrTon",
        ),
        migrations.RemoveField(
            model_name="vendorpolicy",
            name="sourceAddrNpi",
        ),
        migrations.RemoveField(
            model_name="vendorpolicy",
            name="sourceAddrTon",
        ),
    ]
