# Generated by Django 5.2.7 on 2026-05-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("squadServices", "0127_remove_vendorpolicy_addrnpi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operatornetworkcode",
            name="networkName",
        ),
    ]
